/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        paper: 'rgb(var(--color-paper) / <alpha-value>)',
        'paper-raised': 'rgb(var(--color-paper-raised) / <alpha-value>)',
        purple: 'rgb(var(--color-purple) / <alpha-value>)',
        'purple-dark': 'rgb(var(--color-purple-dark) / <alpha-value>)',
        'timer-action': 'rgb(var(--color-timer-action) / <alpha-value>)',
        'timer-action-pressed': 'rgb(var(--color-timer-action-pressed) / <alpha-value>)',
        'on-purple': 'rgb(var(--color-on-purple) / <alpha-value>)',
        'off-white': '#F7F1E3',
        ink: 'rgb(var(--color-ink) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        line: 'rgb(var(--color-line) / <alpha-value>)',
        'strong-line': 'rgb(var(--color-strong-line) / <alpha-value>)',
        'contrast-line': 'rgb(var(--color-contrast-line) / <alpha-value>)',
        'offset-shadow': 'rgb(var(--color-offset-shadow) / <alpha-value>)',
        'nav-surface': 'rgb(var(--color-nav-surface) / <alpha-value>)',
        danger: 'rgb(var(--color-danger) / <alpha-value>)',
        'surface-pressed': 'rgb(var(--color-surface-pressed) / <alpha-value>)',
        viewer: '#141116',
        'viewer-canvas': '#2B272D',
        'viewer-foreground': '#F7F1E3',
        'viewer-muted': '#D8CEBE',
        'folder-red': '#D9554D',
        'folder-green': '#46A758',
        'folder-orange': '#E58A2B',
        'folder-pink': '#D95D8A',
        'folder-blue': '#3F7CCF',
        'folder-teal': '#2E9C91',
        'folder-yellow': '#E2B93F',
        'folder-black': '#2B272D',
        'folder-gray': '#CFCDD2',
      },
      fontFamily: {
        sans: ['DMSans_400Regular'],
        'sans-medium': ['DMSans_600SemiBold'],
        display: ['Fraunces_700Bold'],
      },
      boxShadow: {
        card: '4px 5px 0px rgba(20, 17, 22, 0.95)',
      },
    },
  },
  plugins: [],
};
